# Generated by Django 4.2.1 on 2023-05-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catefory', to='finance_app.category', verbose_name='Category')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.wallet', verbose_name='wallet')),
            ],
        ),
    ]
