# Generated by Django 4.2.1 on 2023-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['wallet'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
